# Generated by Django 4.0 on 2022-02-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=150)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.myuser')),
            ],
        ),
    ]
