# Generated by Django 4.0 on 2022-04-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('id_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.trip')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.myuser')),
            ],
        ),
    ]
