# Generated by Django 4.0 on 2022-04-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_trip_latitude_alter_trip_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='id_trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='id_journey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.journey'),
            preserve_default=False,
        ),
    ]
